#ifndef __CODENOTE_THEME_H__
#define __CODENOTE_THEME_H__

#include "ansicolor.h"

#define COLOR_TITLE FG_BLACK CO_AND BG_YELLOW
#define COLOR_TITLE_FILE_NAME COLOR_TITLE CO_AND CO_UNDERLINE CO_AND CO_REV
#define COLOR_DATA FG_BLACK CO_AND BG_GREEN
#define COLOR_DATA_D FG_BLACK CO_AND BG_CYAN
#define COLOR_WARNING FG_BLACK CO_AND BG_RED_L

#endif
